# -*- coding: utf-8 -*-
{
    'name': 'SPXCORP Pharmacy Dispensing Management',
    'version': '3.1.15',
    'category': 'Healthcare/Pharmacy',
    'summary': 'Patient profiles, prescriptions, dispensing logs, controlled registers, alerts, POS backend linkage and audit reports.',
    'description': 'A production-oriented pharmacy dispensing workflow for Odoo Community: patients, prescriptions, refills, registers, safety alerts, immutable dispensing logs, reports and sales/POS integration hooks.',
    'author': 'SPXCORP Limited',
    'website': 'https://spxcorp.com',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'product', 'stock', 'product_expiry', 'sale_management', 'point_of_sale'],
    'data': [
        'security/pharmacy_security.xml',
        'security/ir.model.access.csv',
        'data/pharmacy_sequences.xml',
        'data/pharmacy_config_data.xml',
        'reports/pharmacy_report_templates.xml',
        'reports/pharmacy_report_actions.xml',
        'views/pharmacy_patient_views.xml',
        'views/pharmacy_drug_views.xml',
        'views/pharmacy_prescription_views.xml',
        'views/pharmacy_dispensing_views.xml',
        'views/pharmacy_register_views.xml',
        'wizards/pharmacy_dispense_wizard_views.xml',
        'wizards/pharmacy_alert_override_wizard_views.xml',
        'views/pharmacy_alert_views.xml',
        'views/pharmacy_audit_views.xml',
        'views/pharmacy_sale_pos_views.xml',
        'views/pharmacy_dashboard_views.xml',
        'views/pharmacy_config_views.xml',
        'views/pharmacy_simple_dispense_wizard_views.xml',
        'views/pharmacy_menu.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'spx_pharmacy_dispensing/static/src/js/pharmacy_pos_safe_button.js',
        ],
    },
    'images': ['static/description/icon.png'],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
}
